//
//  PlacemarkWorker.swift
//  NEWCurrentAddress
//
//  Created by Patrick Pahl on 5/21/18.
//  Copyright (c) 2018 Patrick Pahl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PlacemarkWorker
{
  func doSomeWork()
  {
  }
}
