//
//  MapPresenter.swift
//  NEWCurrentAddress
//
//  Created by Patrick Pahl on 5/18/18.
//  Copyright (c) 2018 Patrick Pahl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

protocol MapPresentationLogic {
    func presentSomething(response: Map.Something.Response)
    func presentRequestForCurrentLocation(response: Map.RequestForCurrentLocation.Response)
    func presentGetCurrentLocation(response: Map.GetCurrentLocation.Response)
    func presentCenterMap(response: Map.CenterMap.Response)
}

class MapPresenter: MapPresentationLogic {
    weak var viewController: MapDisplayLogic?

    // MARK: Do something

    func presentSomething(response: Map.Something.Response) {
        let viewModel = Map.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }

    // MARK: Response for current location

    func presentRequestForCurrentLocation(response: Map.RequestForCurrentLocation.Response){

        var viewModel: Map.RequestForCurrentLocation.ViewModel
        let errorTitle = "Location Disabled"
        let errorMessage = "Please enable location services in the Settings app."

        if response.success {
            viewModel = Map.RequestForCurrentLocation.ViewModel(success: true, errorTitle: nil, errorMessage: nil)
        } else {
            viewModel = Map.RequestForCurrentLocation.ViewModel(success: false, errorTitle: errorTitle, errorMessage: errorMessage)
        }

        viewController?.displayRequestForCurrentLocation(viewModel: viewModel)
    }

    func presentGetCurrentLocation(response: Map.GetCurrentLocation.Response) {

        var viewModel: Map.GetCurrentLocation.ViewModel

        if response.success {
            viewModel = Map.GetCurrentLocation.ViewModel(success: true, errorTitle: nil, errorMessage: nil)
        } else {
            let errorMessage: String
            if response.error?.code == CLError.locationUnknown.rawValue {
                errorMessage = "Location could not be determined."
            } else {
                errorMessage = response.error?.localizedDescription ?? ""
            }

            viewModel = Map.GetCurrentLocation.ViewModel(success: false, errorTitle: "Error", errorMessage: errorMessage)
        }

        viewController?.displayGetCurrentLocation(viewModel: viewModel)
    }

    func presentCenterMap(response: Map.CenterMap.Response) {

    }

}
